### ISSUE TITLE
Why is `/` handled differently from static files?

### ISSUE THREAD

**Issue by wooorm** [pierman1/real-time-web-2#6]
[`index.js`](https://github.com/pierman1/real-time-web-2/blob/dcc7c3af545b610973eb28e58b780447ed7be8f5/index.js#L6-L10):

```js
app.get('/', function(req, res){
    res.sendFile(__dirname + '/public/index.html');
});

app.use(express.static(__dirname + '/public/js'));
```

That could be replaced with `app.use(express.static('public'));` (though some paths to JS files need rewriting too).

**Comment by pierman1** [comment]
Neem ik mee naar de beoordeling net als de andere issues!!! Thanks Titus
